#!/usr/bin/python3

import sys


def factorize_number(n):
    factors = []
    divisor = 2

    while n > 1:
        while n % divisor == 0:
            factors.append(divisor)
            n //= divisor
        divisor += 1

    return factors


def print_factorization(n, factors):
    print(f"{n}={'*'.join(map(str, factors))}")


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        for line in file:
            n = int(line.strip())
            factors = factorize_number(n)
            print_factorization(n, factors)


if __name__ == "__main__":
    main()
