#!/usr/bin/python3

import sys
import math

def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def rho_factorize(n):
    x = 2
    y = 2
    d = 1

    f = lambda x: (x**2 + 1) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = gcd(abs(x - y), n)

    return d, n // d

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

def rsa_factorization(filename):
    with open(filename, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = rho_factorize(n)
            print("{}={}*{}".format(n, p, q))

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    filename = sys.argv[1]
    rsa_factorization(filename)
